### ISSUE TITLE
Bunch of syntax errors when compiling

### ISSUE THREAD

**Issue by TAOcroatia** [gus33000/FocalTechTouch#1]
I'm getting these errors: https://pastebin.com/ydtnBaQK
I'm using Visual Studio 2019, SDK version 10.0.22000.0 and MSVC v142 ARM64 build tools.

With which setup does it compile successfully?

**Comment by gus33000** [comment]
Depending on the Windows SDK version you install you will need to retarget the project by going to project properties and select the right SDK version.

**Comment by TAOcroatia** [comment]
I'm not entierly sure how did the issue get resolved, but it's gone
